# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: ubuntu-latest

trigger: none
pr: none

steps:

- task: UseNode@1
  inputs:
    checkLatest: true

- task: Bash@3
  displayName: "Set Archive Tag"
  inputs:
    targetType: inline
    script: |
      BRANCH=$(Build.SourceBranchName)

      if [ "$BRANCH" = "main" ]; then
        PREFIX="prod"
      else
        PREFIX="pre-prod"
      fi
      ARCHIVE_TAG="${PREFIX}-$(Build.SourceVersion)"
      echo "Archive Tag: $ARCHIVE_TAG"
      echo "##vso[task.setvariable variable=ARCHIVE_TAG]$ARCHIVE_TAG"

- task: Bash@3
  displayName: testing
  inputs:
    targetType: inline
    script:  |
      echo "Testing Tag - $(ARCHIVE_TAG)"
  
- task: ArchiveFiles@2
  displayName: Archive Source
  inputs:
    rootFolderOrFile: '$(Build.SourcesDirectory)'
    includeRootFolder: false
    archiveType: zip
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(ARCHIVE_TAG).zip'
    replaceExistingArchive: true

# - task: CopyFiles@2
#   displayName: "Copy Artifact"
#   inputs:
#     SourceFolder: '$(Build.SourcesDirectory)'
#     Contents: '$(ARCHIVE_TAG).zip'
#     TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: UniversalPackages@0
  inputs:
    command: 'publish'
    publishDirectory: '$(Build.ArtifactStagingDirectory)'
    feedsToUsePublish: 'internal'
    vstsFeedPublish: '00122c08-9d0d-4447-9c18-1d9402ab0153/58250eef-5b76-4ef3-96b7-ed044e59d901'
    vstsFeedPackagePublish: 'first'
    versionOption: 'custom'
    versionPublish: '1.0.0-$(ARCHIVE_TAG)'

# - task: UniversalPackages@1
#   inputs:
#     command: 'publish'
#     feed: 'packages'
#     packageName: 'first'
#     packageVersion: '''1.0-$(ARCHIVE_TAG)'''
#     directory: '$(Build.ArtifactStagingDirectory)'


